### ISSUE TITLE
Compatibility issues with vimwiki

### ISSUE THREAD

**Issue by frankfaustino** [ellisonleao/glow.nvim#88] opened 2022-09-02 00:17 UTC
Glow doesn't work with vimwiki. Trying to preview a markdown file displays "preview only works on markdown files". It seems that nvim detects the file as a "vimwiki" file instead of a "markdown" file (see bottom right of the screenshot below).
<img width="976" alt="with-vimwiki" src="https://user-images.githubusercontent.com/2607929/188033022-8bd5f889-ce1a-48e9-9108-2a61da09f53a.png">

Second screenshot shows Glow working properly with vimwiki uninstalled. Note the file is detected as a markdown file.
<img width="976" alt="without-vimwiki" src="https://user-images.githubusercontent.com/2607929/188033025-f237d747-8528-4b5b-9354-d2606afa516b.png">

**Comment by elliotec** [comment] 2022-09-19 19:52
I went down this rabbit hole and discovered the problem is an issue with Vimwiki rather than glow. [This Reddit thread](https://www.reddit.com/r/vim/comments/vkbyfa/vimwiki_and_vimmarkdown_conflicting/) explains the issue but tl;dr Vimwiki hijacks the filetype of markdown files and tricks vim into thinking they're vimwiki files when you've enabled it to work with markdown, which causes conflicts with any plugin or config specific to markdown filetypes. 

There are workarounds described in that link but the prevailing solution seemed to be to switch to [wiki.vim](https://github.com/lervag/wiki.vim) from vimwiki if you want wiki functionality that actually plays nice with markdown files. This is what I did and it fixed all my other markdown issues.

**Comment by ellisonleao** [comment] 2022-09-19 20:28
we can add vimwiki filetype to the allowed extensions but you will still get issues with the links and possibly other ones. Will that work?

**Comment by elliotec** [comment] 2022-09-20 18:52
@ellisonleao I think that will work to get Glow to function, but to your point it wont fix all the other markdown issues people will run into using vimwiki. Probably good enough for a lot of folks though!

**Comment by ellisonleao** [comment] 2022-09-22 20:23
Just pushed a commit allowing vimwiki filetypes and .wiki extensions. This will not fix the rendering part though.

**Closed by ellisonleao** 2022-09-22 20:23 UTC
