### ISSUE TITLE
Blank output

### ISSUE THREAD

**Issue by siduck** [ellisonleao/glow.nvim#54] opened 2021-11-19 03:45 UTC
Hi I installed the plugin and :Glow gives me a blank floating window 

![image](https://user-images.githubusercontent.com/59060246/142561413-fbb21a91-fc5c-4c15-8f5a-77d58773c96b.png)

**Comment by siduck** [comment] 2021-11-19 03:47
Pressing i + enter in the floating window shows the preview but it also shows "process exited"

![image](https://user-images.githubusercontent.com/59060246/142561519-90b914ac-b9aa-47dc-bd75-524b2adef889.png)

**Comment by ellisonleao** [comment] 2021-11-19 13:45
[Process exited] is expected, however the black screen at the beginning is not. Can you share you OS specs, neovim version please?

**Comment by siduck** [comment] 2021-11-19 14:38
> [Process exited] is expected, however the black screen at the beginning is not. Can you share you OS specs, neovim version please?

```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/neovim-0.5.1/build/config -I/builddir/neovim-0.5.1/src -I/usr/include -I/builddir/neovim-0.5.1/build/src/nvim/auto -I/builddir/neovim-0.5.1/build/include
Compiled by void-buildslave@a-fsn-de
```

OS : void linux

**Comment by siduck** [comment] 2021-11-19 14:39
@ellisonleao I tried a minimal config and the plugin works , Im not sure whats the issue with my config. does this plugin depend on plenary or another plugin?

**Comment by ellisonleao** [comment] 2021-11-19 16:42
@siduck no, it just depends on the glow binary and a neovim 0.5+ version

**Comment by Limaomao821** [comment] 2021-11-24 03:35
in #48, I came across a similar problem. The exact problem could be described as follows:

1. after system reboot, glow.nvim works just as fine (the very first time use glow.nvim).

2. after first use, glow.nvim will give blank output.

3. reboot system and step 1 and 2 will repeat.

I wonder @siduck may have the same issue as me?

environment: Linux 5.11.0-40-generic #44~20.04.2-Ubuntu SMP x86_64 GNU/Linux, neovim v0.6.0-dev+516-g4a618b00b

**Comment by Limaomao821** [comment] 2021-11-24 11:26
It seems that everythings work fine before termopen().

Could it be some misconfigurations on buf options?

**Comment by siduck** [comment] 2021-11-24 12:25
> It seems that everythings work fine before termopen().
> 
> Could it be some misconfigurations on buf options?

wym?

**Comment by Limaomao821** [comment] 2021-11-24 12:43
> > It seems that everythings work fine before termopen().
> > Could it be some misconfigurations on buf options?
> 
> wym?

In glow.nvim source code lua/glow.lua:209, comment this line and try glow.nvim.

Also, try :lua vim.fn.termopen("glow path/to/file"), it works.

So I suspect something not right about buf options.

**Comment by siduck** [comment] 2021-11-30 05:02
> > > It seems that everythings work fine before termopen().
> > > Could it be some misconfigurations on buf options?
> > 
> > 
> > wym?
> 
> In glow.nvim source code lua/glow.lua:209, comment this line and try glow.nvim.
> 
> Also, try :lua vim.fn.termopen("glow path/to/file"), it works.
> 
> So I suspect something not right about buf options.

I commented that line and executed that command , it worked

**Comment by ellisonleao** [comment] 2022-07-15 01:55
guys can you pull latest and close this issue if the problem is resolved?

**Closed** 2022-07-15 01:56 UTC
