### ISSUE TITLE
Glow syntax highlight / color(s) woundn't work on windows platform

### ISSUE THREAD

**Issue by shrkamat** [ellisonleao/glow.nvim#61] opened 2022-01-04 16:08 UTC
I find glow syntax highlighting don't work on Windows. I have another Ubuntu machine with same neovim init scripts & glow syntax coloring works fine there. I am using `neovim 0.6.1` with packer on both Ubuntu and Windows.

![Failure](https://i.imgur.com/xAVdSE8.png)

I have intstalled glow to this path & updated `glow_binary_path` 

```
vim.g.glow_binary_path="c:\\Neovim\\bin"
```

P.S. this woks fine on [windows terminal](https://github.com/microsoft/terminal) prompt too.
![Success](https://i.imgur.com/2eZ6HG9.png)

**Comment by ellisonleao** [comment] 2022-01-08 14:48
Hey @shrkamat thanks for the report! Unfortunately i don't have a way to test this on windows machines now. If you have a workaround just let me know and i can make the changes.

**Comment by pynappo** [comment] 2022-12-28 15:13
FWIW, I cannot reproduce this issue:

- Windows 11
- Windows Terminal
- `nvim` 0.9 nightly installed through `scoop`
- `pwsh` 7.2.8
- `glow` installed through `scoop`:

init.lua:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

require('lazy').setup({
  "ellisonleao/glow.nvim",
})

```

(obviously half the text blends in with the background with how the default neovim colorscheme works out with my terminal colorscheme, but you can still see there's highlighting)

![Image with a README from my neovim config + some of OP's text](https://user-images.githubusercontent.com/43484729/209832262-1cef66ef-272c-46d3-acc0-dd9c99ba1c5c.png)

If OP's still having this issue, are there any more details of your config that you could provide?

**Comment by ellisonleao** [comment] 2023-02-10 00:23
hey @pynappo can you update to latest and try again please?

**Comment by pynappo** [comment] 2023-02-10 12:03
https://github.com/ellisonleao/glow.nvim/commit/83f184063095ab9928175d9c4abafd8d0ac83700 broke functionality for me, I think `nvim_open_term()` just doesn't work great with Windows. I kept getting zero output no matter what args I put into the glow jobstart cmd when trying to fix it. I've just submitted a tiny PR with a workaround that just calls `termopen()` for windows, it works as normal once I add those lines.

**Comment by ellisonleao** [comment] 2023-03-03 03:02
@pynappo can you pull latest and see if latest glow version + glow.nvim works for you?

**Comment by pynappo** [comment] 2023-03-05 11:38
> @pynappo can you pull latest and see if latest glow version + glow.nvim works for you?

latest works for me now :)

**Comment by ellisonleao** [comment] 2023-03-05 20:40
closing it them. @shrkamat feel free to reopen it if you still have issues

**Closed by ellisonleao** 2023-03-05 20:40 UTC
Labels: help wanted, windows
